import SwiftUI

struct ScreenTemplate: Identifiable {
    let id = UUID()
    let title: String
    let subtitle: String
    let icon: String
    let accentColor: Color
    let screen: Screen

    static let all: [ScreenTemplate] = [
        onboarding, login, profile, settings, homeFeed, emptyState
    ]

    static let onboarding = ScreenTemplate(
        title: "Onboarding",
        subtitle: "Welcome screen with hero image, title, and CTA button.",
        icon: "hand.wave",
        accentColor: Color(red: 0.45, green: 0.52, blue: 0.96),
        screen: Screen(name: "Onboarding", blocks: [
            CanvasBlock(kind: .symbol, content: "", symbolName: "star.fill", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .primary,
                        fillColor: Color(red: 0.45, green: 0.52, blue: 0.96),
                        spacingBefore: 24, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1.2, listItems: []),
            CanvasBlock(kind: .heroTitle, content: "Welcome to the App", symbolName: "", alignment: .center,
                        fontSize: 30, fontWeight: .bold,
                        textColor: Color(red: 0.12, green: 0.14, blue: 0.24), fillColor: .clear,
                        spacingBefore: 20, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .bodyText, content: "Discover amazing features that help you get things done faster and smarter.", symbolName: "", alignment: .center,
                        fontSize: 17, fontWeight: .regular,
                        textColor: Color(red: 0.40, green: 0.42, blue: 0.52), fillColor: .clear,
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .primaryButton, content: "Get Started", symbolName: "", alignment: .center,
                        fontSize: 18, fontWeight: .semibold, textColor: .white,
                        fillColor: Color(red: 0.29, green: 0.46, blue: 0.96),
                        spacingBefore: 28, horizontalPadding: 20, verticalPadding: 16,
                        cornerRadius: 16, symbolScale: 1, listItems: []),
        ])
    )

    static let login = ScreenTemplate(
        title: "Login",
        subtitle: "Email and password form with sign-in button.",
        icon: "person.badge.key",
        accentColor: Color(red: 0.38, green: 0.82, blue: 0.60),
        screen: Screen(name: "Login", blocks: [
            CanvasBlock(kind: .heroTitle, content: "Sign In", symbolName: "", alignment: .leading,
                        fontSize: 28, fontWeight: .bold,
                        textColor: Color(red: 0.12, green: 0.14, blue: 0.24), fillColor: .clear,
                        spacingBefore: 32, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .bodyText, content: "Welcome back! Enter your credentials to continue.", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.50, green: 0.52, blue: 0.58), fillColor: .clear,
                        spacingBefore: 8, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .caption, content: "EMAIL", symbolName: "", alignment: .leading,
                        fontSize: 11, fontWeight: .semibold,
                        textColor: Color(red: 0.45, green: 0.47, blue: 0.54), fillColor: .clear,
                        spacingBefore: 24, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .textField, content: "Email address", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.60, green: 0.60, blue: 0.64),
                        fillColor: Color(red: 0.95, green: 0.95, blue: 0.97),
                        spacingBefore: 6, horizontalPadding: 14, verticalPadding: 14,
                        cornerRadius: 12, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .caption, content: "PASSWORD", symbolName: "", alignment: .leading,
                        fontSize: 11, fontWeight: .semibold,
                        textColor: Color(red: 0.45, green: 0.47, blue: 0.54), fillColor: .clear,
                        spacingBefore: 16, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .textField, content: "Password", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.60, green: 0.60, blue: 0.64),
                        fillColor: Color(red: 0.95, green: 0.95, blue: 0.97),
                        spacingBefore: 6, horizontalPadding: 14, verticalPadding: 14,
                        cornerRadius: 12, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .primaryButton, content: "Sign In", symbolName: "", alignment: .center,
                        fontSize: 17, fontWeight: .semibold, textColor: .white,
                        fillColor: Color(red: 0.38, green: 0.82, blue: 0.60),
                        spacingBefore: 20, horizontalPadding: 20, verticalPadding: 16,
                        cornerRadius: 14, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .linkButton, content: "Forgot Password?", symbolName: "", alignment: .center,
                        fontSize: 15, fontWeight: .medium,
                        textColor: Color(red: 0.38, green: 0.82, blue: 0.60), fillColor: .clear,
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
        ])
    )

    static let profile = ScreenTemplate(
        title: "Profile",
        subtitle: "Avatar, name, badge, and settings rows.",
        icon: "person.crop.circle",
        accentColor: Color(red: 0.56, green: 0.48, blue: 0.96),
        screen: Screen(name: "Profile", blocks: [
            CanvasBlock(kind: .avatar, content: "", symbolName: "person.fill", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .white,
                        fillColor: Color(red: 0.56, green: 0.48, blue: 0.96),
                        spacingBefore: 24, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1.2, listItems: []),
            CanvasBlock(kind: .heroTitle, content: "John Appleseed", symbolName: "", alignment: .center,
                        fontSize: 24, fontWeight: .bold,
                        textColor: Color(red: 0.12, green: 0.14, blue: 0.24), fillColor: .clear,
                        spacingBefore: 16, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .badge, content: "Pro Member", symbolName: "", alignment: .center,
                        fontSize: 13, fontWeight: .semibold, textColor: .white,
                        fillColor: Color(red: 0.56, green: 0.48, blue: 0.96),
                        spacingBefore: 8, horizontalPadding: 10, verticalPadding: 4,
                        cornerRadius: 12, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .divider, content: "", symbolName: "", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .clear,
                        fillColor: Color(red: 0.78, green: 0.78, blue: 0.80),
                        spacingBefore: 20, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .iconRow, content: "Edit Profile", symbolName: "person.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.56, green: 0.48, blue: 0.96),
                        spacingBefore: 12, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: [""]),
            CanvasBlock(kind: .iconRow, content: "Notifications", symbolName: "bell.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.96, green: 0.36, blue: 0.42),
                        spacingBefore: 4, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: ["On"]),
            CanvasBlock(kind: .iconRow, content: "Privacy", symbolName: "lock.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.34, green: 0.80, blue: 0.46),
                        spacingBefore: 4, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: [""]),
            CanvasBlock(kind: .iconRow, content: "Help & Support", symbolName: "questionmark.circle.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.96, green: 0.56, blue: 0.41),
                        spacingBefore: 4, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: [""]),
        ])
    )

    static let settings = ScreenTemplate(
        title: "Settings",
        subtitle: "Info rows, toggles, sliders, and grouped options.",
        icon: "gearshape",
        accentColor: Color(red: 0.50, green: 0.55, blue: 0.62),
        screen: Screen(name: "Settings", blocks: [
            CanvasBlock(kind: .heroTitle, content: "Settings", symbolName: "", alignment: .leading,
                        fontSize: 28, fontWeight: .bold,
                        textColor: Color(red: 0.12, green: 0.14, blue: 0.24), fillColor: .clear,
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .searchBar, content: "Search settings...", symbolName: "magnifyingglass",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.60, green: 0.60, blue: 0.64),
                        fillColor: Color(red: 0.95, green: 0.95, blue: 0.97),
                        spacingBefore: 16, horizontalPadding: 12, verticalPadding: 10,
                        cornerRadius: 10, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .caption, content: "PREFERENCES", symbolName: "", alignment: .leading,
                        fontSize: 11, fontWeight: .semibold,
                        textColor: Color(red: 0.45, green: 0.47, blue: 0.54), fillColor: .clear,
                        spacingBefore: 20, horizontalPadding: 4, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .toggle, content: "Dark Mode", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.34, green: 0.80, blue: 0.46),
                        spacingBefore: 8, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .toggle, content: "Push Notifications", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.34, green: 0.80, blue: 0.46),
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 0, listItems: []),
            CanvasBlock(kind: .slider, content: "Text Size", symbolName: "", alignment: .leading,
                        fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.29, green: 0.56, blue: 0.96),
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 0.65, listItems: []),
            CanvasBlock(kind: .caption, content: "GENERAL", symbolName: "", alignment: .leading,
                        fontSize: 11, fontWeight: .semibold,
                        textColor: Color(red: 0.45, green: 0.47, blue: 0.54), fillColor: .clear,
                        spacingBefore: 20, horizontalPadding: 4, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .iconRow, content: "Account", symbolName: "person.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.29, green: 0.56, blue: 0.96),
                        spacingBefore: 8, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: [""]),
            CanvasBlock(kind: .iconRow, content: "Privacy", symbolName: "lock.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.34, green: 0.80, blue: 0.46),
                        spacingBefore: 4, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: [""]),
            CanvasBlock(kind: .iconRow, content: "About", symbolName: "info.circle.fill",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.50, green: 0.55, blue: 0.62),
                        spacingBefore: 4, horizontalPadding: 16, verticalPadding: 12,
                        cornerRadius: 12, symbolScale: 1, listItems: ["v1.0"]),
            CanvasBlock(kind: .secondaryButton, content: "Log Out", symbolName: "", alignment: .center,
                        fontSize: 16, fontWeight: .semibold,
                        textColor: Color(red: 0.96, green: 0.36, blue: 0.36), fillColor: .clear,
                        spacingBefore: 24, horizontalPadding: 20, verticalPadding: 12,
                        cornerRadius: 14, symbolScale: 1, listItems: []),
        ])
    )

    static let homeFeed = ScreenTemplate(
        title: "Home Feed",
        subtitle: "Header, search, cards, and content.",
        icon: "house",
        accentColor: Color(red: 0.96, green: 0.56, blue: 0.41),
        screen: Screen(name: "Home", blocks: [
            CanvasBlock(kind: .heroTitle, content: "Good Morning", symbolName: "", alignment: .leading,
                        fontSize: 28, fontWeight: .bold,
                        textColor: Color(red: 0.12, green: 0.14, blue: 0.24), fillColor: .clear,
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .searchBar, content: "Search...", symbolName: "magnifyingglass",
                        alignment: .leading, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.60, green: 0.60, blue: 0.64),
                        fillColor: Color(red: 0.95, green: 0.95, blue: 0.97),
                        spacingBefore: 16, horizontalPadding: 12, verticalPadding: 10,
                        cornerRadius: 10, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .segmentedControl, content: "", symbolName: "", alignment: .center,
                        fontSize: 14, fontWeight: .medium,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.93, green: 0.93, blue: 0.95),
                        spacingBefore: 16, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 8, symbolScale: 0,
                        listItems: ["All", "Recent", "Popular"]),
            CanvasBlock(kind: .card, content: "Getting Started", symbolName: "bolt.fill",
                        alignment: .leading, fontSize: 17, fontWeight: .semibold,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.97, green: 0.97, blue: 0.98),
                        spacingBefore: 16, horizontalPadding: 16, verticalPadding: 14,
                        cornerRadius: 16, symbolScale: 1,
                        listItems: ["Complete your profile to unlock all features."]),
            CanvasBlock(kind: .card, content: "Weekly Summary", symbolName: "chart.bar.fill",
                        alignment: .leading, fontSize: 17, fontWeight: .semibold,
                        textColor: Color(red: 0.15, green: 0.17, blue: 0.28),
                        fillColor: Color(red: 0.97, green: 0.97, blue: 0.98),
                        spacingBefore: 10, horizontalPadding: 16, verticalPadding: 14,
                        cornerRadius: 16, symbolScale: 1,
                        listItems: ["You had 12 sessions this week. Keep it up!"]),
            CanvasBlock(kind: .progressBar, content: "", symbolName: "", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .clear,
                        fillColor: Color(red: 0.96, green: 0.56, blue: 0.41),
                        spacingBefore: 12, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 4, symbolScale: 0.45, listItems: []),
            CanvasBlock(kind: .caption, content: "45% toward your weekly goal", symbolName: "", alignment: .leading,
                        fontSize: 12, fontWeight: .regular,
                        textColor: Color(red: 0.50, green: 0.52, blue: 0.58), fillColor: .clear,
                        spacingBefore: 4, horizontalPadding: 4, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
        ])
    )

    static let emptyState = ScreenTemplate(
        title: "Empty State",
        subtitle: "Placeholder for no-content screens.",
        icon: "tray",
        accentColor: Color(red: 0.60, green: 0.60, blue: 0.66),
        screen: Screen(name: "Empty State", blocks: [
            CanvasBlock(kind: .spacer, content: "", symbolName: "", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .clear, fillColor: .clear,
                        spacingBefore: 80, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .symbol, content: "", symbolName: "tray", alignment: .center,
                        fontSize: 0, fontWeight: .regular, textColor: .primary,
                        fillColor: Color(red: 0.70, green: 0.70, blue: 0.74),
                        spacingBefore: 0, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 0.8, listItems: []),
            CanvasBlock(kind: .heroTitle, content: "Nothing Here Yet", symbolName: "", alignment: .center,
                        fontSize: 22, fontWeight: .semibold,
                        textColor: Color(red: 0.30, green: 0.32, blue: 0.38), fillColor: .clear,
                        spacingBefore: 16, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .bodyText, content: "Add your first item to get started.", symbolName: "",
                        alignment: .center, fontSize: 16, fontWeight: .regular,
                        textColor: Color(red: 0.50, green: 0.52, blue: 0.58), fillColor: .clear,
                        spacingBefore: 8, horizontalPadding: 0, verticalPadding: 0,
                        cornerRadius: 0, symbolScale: 1, listItems: []),
            CanvasBlock(kind: .primaryButton, content: "Add Item", symbolName: "", alignment: .center,
                        fontSize: 16, fontWeight: .semibold, textColor: .white,
                        fillColor: Color(red: 0.29, green: 0.46, blue: 0.96),
                        spacingBefore: 24, horizontalPadding: 20, verticalPadding: 14,
                        cornerRadius: 14, symbolScale: 1, listItems: []),
        ])
    )
}
